### ISSUE TITLE
Cannot insert NULL into DateTime column

### ISSUE THREAD

**Issue by ChristofColle-VIVES** [MarkMpn/Sql4Cds#420] opened 2024-01-19 08:08 UTC
I cannot insert a new record with a (nullable) DateTime column, if I try to insert a NULL value into that column.

E.g.
```
INSERT INTO [dbo].[vivnavor_erkenningsnummer] (
	[vivnavor_name]
	, [vivnavor_instanties]
	, [vivnavor_opleiding]
	, [vivnavor_certificatie]
	, [vivnavor_begindatum]
	, [vivnavor_einddatum]
	, [vivnavor_geldigheidsvoorwaarden]
)
SELECT TOP(1) 
	e.[vivnavor_name]
	, e.[vivnavor_instanties]
	, o.[vivnavor_aanbodid]
	, e.[vivnavor_certificatie]
	, e.[vivnavor_begindatum]
	, e.[vivnavor_einddatum]
	, e.[vivnavor_geldigheidsvoorwaarden]

FROM [dbo].[vivnavor_erkenningsnummer] AS e
INNER JOIN [dbo].[vivnavor_aanbod] AS r
	ON r.[vivnavor_aanbodid] = e.[vivnavor_opleiding]
INNER JOIN [dbo].[vivnavor_aanbod] AS o
	ON o.[vivnavor_code] = REPLACE(r.[vivnavor_code], '+', '#')

WHERE e.[statecode] = 0
	AND r.[vivnavor_code] LIKE '+%'
	AND e.[vivnavor_begindatum] IS NULL
```

**Comment by MarkMpn** [comment] 2024-01-19 11:45
I can't reproduce an error with this. If I try:

```sql
INSERT INTO contact (birthdate) VALUES (null);
INSERT INTO contact (birthdate) SELECT birthdate FROM contact WHERE contactid = @@IDENTITY;
```

I correctly get two new contact records, each with a null birthdate field. Can you share the error you're getting with your query, and/or create a similar query using standard tables so I can reproduce it?

**Comment by ChristofColle-VIVES** [comment] 2024-01-19 14:30
hi Mark, thank you for your quick reply!

Can you try the following please?
```
INSERT INTO [dbo].[contact] (
	[firstname],
	[lastname],
	[birthdate]
)
SELECT 'Christof'
	, 'Colle'
	, CAST('1980/10/20' AS datetime)
;

INSERT INTO [dbo].[contact] (
	[firstname],
	[lastname],
	[birthdate]
)
SELECT 'Christof'
	, 'Colle'
	, NULL
;

INSERT INTO [dbo].[contact] (
	[firstname],
	[lastname],
	[birthdate]
)
SELECT [firstname],
	[lastname],
	[birthdate]
FROM [dbo].[contact];
```

**Comment by ChristofColle-VIVES** [comment] 2024-01-19 14:38
Update, I've split-up my previous example.
First simply inserting 2 contacts, one with and one without a birthdate value.

Then, in a new batch, I'm trying to duplicate them with my INSERT INTO ... SELECT ... statement.

My response is as follows :

> Inserting 2 Contactpersonen...
> **Specified cast is not valid.**
> 
> Completion time: 2024-01-19T15:35:58.2636684+01:00

**Comment by MarkMpn** [comment] 2024-01-19 15:32
I can still run these queries without error. Can you please let me know where you are running SQL 4 CDS (in XrmToolBox, SSMS or Azure Data Studio) and the results of `SELECT @@VERSION`?

**Comment by ChristofColle-VIVES** [comment] 2024-01-19 15:58
I'm running these queries in SSMS.

The output of @@VERSION is :
```
Microsoft SQL Azure (RTM) - 12.0.2000.8
                Nov  2 2023 01:40:17
                Copyright (C) 2022 Microsoft Corporation
```

Kind regards, Christof

**Comment by MarkMpn** [comment] 2024-01-19 19:41
Thanks, can you try adding the `FORCE_SQL_4_CDS` hint to your query, e.g.:

```sql
INSERT INTO [dbo].[contact] (
	[firstname],
	[lastname],
	[birthdate]
)
SELECT [firstname],
	[lastname],
	[birthdate]
FROM [dbo].[contact]
WHERE [firstname] = 'Christof' 
	AND [lastname] = 'Colle'
OPTION(USE HINT('FORCE_SQL_4_CDS'));
```

I believe there's a bug with the NULL handling when it uses the TDS Endpoint, and this forces it to convert the SELECT to FetchXML instead. If that works for you I should be able to get this fixed in the next update so you won't need this workaround in future.

**Comment by ChristofColle-VIVES** [comment] 2024-01-22 13:49
That works, Mark!
Thanks for the workaround suggestion!

Do you want me to close this issue?
Or will you close it yourself after providing a patch in the next release?

**Comment by MarkMpn** [comment] 2024-01-22 14:15
I’ll close it once I merge the patch in, thanks for letting me know!

**Closed** 2024-01-24 22:43 UTC
