### ISSUE TITLE
Multiple INNER JOIN no longer working

### ISSUE THREAD

**Issue by Edwin-VC** [MarkMpn/Sql4Cds#357] opened 2023-09-15 12:47 UTC
@MarkMpn Great work developing and maintaining this tool. A real time saver.

Until recently I was able to use multiple INNER JOIN statements to compare data for multiple environments and once:

SELECT *
FROM [ENV-A].dbo.queue as a
           INNER JOIN
           [ENV-B].dbo.queue as b
           ON a.key = b.key
           INNER JOIN
           [ENV-B].dbo.queue as c
           ON c.key = c.key
           
Now when I open a saved query with this pattern, I get the following error message on Execute:
**The given key was not present in the dictionary.
See the Execution Plan tab for details of where this error occurred**

The execution plan does not provide any additional information.

This works fine with 1 inner-join, but adding the 2nd inner-join will now throw this error.

What am I doing wrong?

**Comment by MarkMpn** [comment] 2023-09-15 18:17
I can't reproduce this at the moment - can you post the full exact query please?

In your final join you've got the criteria `c.key = c.key` - I assume this is a typo and should actually be `a.key = c.key`?

**Comment by MarkMpn** [comment] 2023-09-18 20:33
If you see a merge join operator followed by a sort operator in the execution plan like in #359, this should be fixed in the next update.

**Comment by Edwin-VC** [comment] 2023-09-19 05:18
Hi Mark,

Thank you for following up.

You are right about my typo.

Here is a sample query that did allow me to compare different environments, but does not work anymore with the second Join. If I remove a second Join, either ACC or PRD, the query does work.

/* COMPARE QUEUES */
SELECT dev.queueid,
       dev.msdyn_queuetypename AS dev_type,
       dev.name AS dev_name,
       dev.ownerid AS dev_owner,
       acc.queueid,
       acc.name AS acc_name,
       acc.owneridname AS acc_owner,
       prd.queueid,
       prd.name AS prod_name,
       prd.owneridname AS prod_owner
FROM   [XXX | DEV].dbo.queue AS dev
       INNER JOIN
       [XXX | ACC].dbo.queue AS acc
       ON dev.queueid = acc.queueid
       INNER JOIN
       [XXX | PROD].dbo.queue AS prd
       ON dev.queueid = prd.queueid
WHERE  dev.name NOT LIKE '%#%' AND dev.name NOT LIKE '<%>';

Let me know if there is a workaround.

Thank you again.

Edwin

**Comment by MarkMpn** [comment] 2023-09-20 07:39
I believe this is the same bug as #359, I'm hoping to get an update out next week to resolve this. In the meantime you can try installing an earlier version using the version selector in the tool library in XrmToolBox.

**Comment by Edwin-VC** [comment] 2023-09-20 11:32
Hi Mark,

Thank you for following up, and even more for resolving this issue. I will use the work-around and look forward to the update.

Cheers!
Edwin

**Comment by MarkMpn** [comment] 2023-09-30 11:47
This should be fixed now in v7.6, please let me know if you still have any problems.

**Closed by MarkMpn** 2023-09-30 11:47 UTC

**Comment by Edwin-VC** [comment] 2023-10-01 13:24
Thank you so much again.

I’ve updated the plugin and also the new version works again like a charm.

I could not find a way to make a donation. Let me know if you have such an option.

Edwin

**Comment by MarkMpn** [comment] 2023-10-01 22:37
Sure, there's a link in XrmToolBox:

![image](https://github.com/MarkMpn/Sql4Cds/assets/31017244/13708621-f9ff-4169-b817-e8318a4c6b20)

or directly at https://www.paypal.com/donate/?cmd=_donations&business=donate@markcarrington.dev&lc=EN&item_name=XrmToolBox+Tool+Donation&currency_code=GBP&bn=PP%2dDonationsBF

Thanks!
