### ISSUE TITLE
SQL 4 CDS is not showing all results

### ISSUE THREAD

**Issue by SpaceManMat** [MarkMpn/Sql4Cds#481] opened 2024-06-03 23:40 UTC
I have a query that returns more than 100 records as long as I don't select the primary key from one table. When I select the primary key it only displays 2 records and it shows and red exclamation mark with the following error on one of those records:  ReadOnly Data is Modified.

The query is as follows:
```
SELECT top 100
     app.fgm_grantprogrammeid
     , wkf.fgm_WorkflowId
FROM fgm_applicationgrant AS app
, fgm_workflow AS wkf  
WHERE app.fgm_grantprogrammeid = wkf.fgm_ProgramId
AND wkf.fgm_workflowid IN ('{596ddbc5-7496-ea11-a812-000d3a794f5d}', '{8ad95152-0dab-4074-80fb-c2bf13475ca9}')
```

If I run it as is it will display the following
![image](https://github.com/MarkMpn/Sql4Cds/assets/27044773/13c9e58e-3e81-4da2-9192-3f6966636bd7)

When I comment out wkf.fgm_WorkflowId from the Select it returns 100 records
![image](https://github.com/MarkMpn/Sql4Cds/assets/27044773/726be016-9c5f-4cde-a295-5204537b0fb7)

Using the Convert function produces the following FetchXML, which when run will return 100 records:
```
<fetch xmlns:generator='MarkMpn.SQL4CDS' top='100'>
  <entity name='fgm_applicationgrant'>
    <attribute name='fgm_grantprogrammeid' />
    <attribute name='fgm_applicationgrantid' />
    <link-entity name='fgm_workflow' to='fgm_grantprogrammeid' from='fgm_programid' alias='wkf' link-type='inner'>
      <attribute name='fgm_workflowid' />
      <filter>
        <condition attribute='fgm_workflowid' operator='in'>
          <value>{596ddbc5-7496-ea11-a812-000d3a794f5d}</value>
          <value>{8ad95152-0dab-4074-80fb-c2bf13475ca9}</value>
        </condition>
      </filter>
      <order attribute='fgm_workflowid' />
    </link-entity>
    <order attribute='fgm_applicationgrantid' />
  </entity>
</fetch>
```

I am currently on the latest version (9.0.1)
I think a recent update has caused this issue.

**Comment by SpaceManMat** [comment] 2024-06-03 23:44
Just saw #479 this looks like the same or a related issue

**Comment by MarkMpn** [comment] 2024-06-05 19:07
Thanks for the details, this does look like a duplicate of #479 so I'm closing this one now.

**Closed by MarkMpn** 2024-06-05 19:07 UTC
