### ISSUE TITLE
Querying data that does not contain a null.

### ISSUE THREAD

**Issue by NathanHealea** [MarkMpn/Sql4Cds#294] opened 2023-05-08 22:44 UTC
What is the correct way to query for non-null data? 

I've tried the following implementation and keep getting the same error back.
`where systemuser.callinguserid is not NULL`
`where systemuser.callinguserid <> NULL`
`where systemuser.callinguserid != NULL`

Here is the error I get back.
```
Encountered unsupported attribute name: 'identityid' when converting entity expression to SQL.
See the Execution Plan tab for details of where this error occurred
```
![image](https://user-images.githubusercontent.com/6578985/236953045-bcc7853b-0a8e-46bb-b65b-b280c262242a.png)

Here is the full SQL I'm trying to run for context
``` SQL
SELECT
    TOP(100)
    audit.regardingobjectid,
    audit.regardingobjectidname,
    audit.regardingobjectidtype,
    audit.createdon,
    audit.userid,
    systemuser.domainname,
    systemuser.firstname,
    systemuser.lastname,
    audit.action,
    audit.actionname,
    audit.operation,
    audit.operationname,
    audit.callinguserid,
    audit.callinguseridname,
    audit.objectid,
    audit.objectidname,
    audit.objectidtype,
    audit.attributemask,
    audit.changedata
FROM audit
LEFT JOIN
    systemuser
    ON audit.userid = systemuser.systemuserid
Where systemuser.callinguseridis is not NULL
```

**Comment by MarkMpn** [comment] 2023-05-09 18:39
`IS NOT NULL` is the correct syntax.

I can't reproduce the error with this query. For me this query fails with the error `Unknown column: systemuser.callinguseridis`.

`callinguserid` is an attribute on the `audit` entity, not `systemuser`, so if I adjust the WHERE clause on this query to:

```sql
Where audit.callinguserid is not NULL
```

the query then runs as expected.

Do you have another query that triggers this error? When you do get the error, can you also double-click on the FetchXML node in the execution plan to get the FetchXML that it's executing and copy that here too? Finally, can you also let me know whether you are running this query against an on-prem or online instance?

**Comment by NathanHealea** [comment] 2023-05-15 19:38
@MarkMpn Thanks for the information. I have not had a chance to retry my query with the suggested changes.

Once I get some free time I will try to run a second query and get you the FetchXML plan for when the error is being caused.

**Comment by NathanHealea** [comment] 2023-05-16 22:19
On the same line, querying the same entities, I recieve the following error when running the following query. 

```SQL 
SELECT
    FORMAT(audit.createdon,'MM/dd/yyyy','en-US') as createondate,
    FORMAT(audit.createdon,'hh:mm:ss tt') as createontime,
    audit.userid,
    systemuser.domainname,
    systemuser.firstname,
    systemuser.lastname,
    audit.action,
    audit.actionname,
    audit.operation,
    audit.operationname,
    audit.callinguserid,
    audit.callinguseridname,
    entity.objecttypecode,
    audit.objectid,
    audit.objectidname,
    audit.objectidtype,
    audit.attributemask,
    audit.changedata    
FROM audit
LEFT JOIN
    systemuser
    ON audit.userid = systemuser.systemuserid
LEFT JOIN
    metadata.entity as entity
    on entity.logicalname = audit.objectidtype
ORDER BY 
    FORMAT(audit.createdon,'MM/dd/yyyy','en-US') ASC, 
    FORMAT(audit.createdon,'hh:mm:ss tt') ASC
```

**Comment by MarkMpn** [comment] 2023-05-17 18:49
Thanks for these details. It looks like there's a bug in the audit data provider that means it doesn't support filters like

```xml
<condition attribute='lastname' entityname='systemuser' operator='ne' value='SYSTEM' />
```

I'll have a workaround for this in the next update.

```sql
audit.objectidtype is not 'audit'
```

is not valid SQL - `IS` is to be used for null queries, i.e. `IS NULL` or `IS NOT NULL`. Comparing to other values should be done with `=` or `<>`

```
The type initializer for 'MarkMpn.Sql4Cds.Engine.ExecutionPlan.MetadataQueryNode' threw an exception.
```

This one appears to be due to some files missing from the SSMS package, I'll investigate for the next update. In the meantime, this query should work in the XrmToolBox version.

**Comment by NathanHealea** [comment] 2023-05-17 22:28
@MarkMpn thanks for the update, 

I found another interesting bug related to the audit queries.

When I run 

```SQL 
SELECT
    * 
FROM audit
```
The objectidtype shows the entity that was updated.

However, if there is any modification to the query, then the data return in the `objectidtype` column for all records equals `audit`

The below query count then number of audit logs that pertain to a specific objectidtype (aka entity).

```SQL
SELECT   
         objectidtype,
         COUNT('x') AS AuditLogsRecords
FROM     audit
GROUP BY objectidtype;
```

**Comment by MarkMpn** [comment] 2023-05-18 07:27
Yes, this is the same as #296 and will be fixed in the next update. I've definitely been learning a lot about how the audit entity works recently!

**Comment by NathanHealea** [comment] 2023-05-18 16:03
@MarkMpn do you know when this issue will be released?

**Comment by MarkMpn** [comment] 2023-05-19 14:09
Probably in the next couple of weeks, I'm just exploring a few other related areas to try and make sure I've covered all the other ways the audit entity is different from normal.

**Closed** 2023-06-12 07:19 UTC
