### ISSUE TITLE
Suggestion: XrmToolBox SQL Editor Comments Short Cuts

### ISSUE THREAD

**Issue by s1m0nj** [MarkMpn/Sql4Cds#253] opened 2022-10-01 09:06 UTC
Hi,

Love your tool and use it frequently.  It would be even better if it supported the shortcut to create comments while writing SQL just like VS and SSMS.

The keyboard shortcut to comment text is CTRL + K, CTRL + C. 
The keyboard shortcut to uncomment text is CTRL + K, CTRL + U

https://learn.microsoft.com/en-us/sql/ssms/tutorials/ssms-tricks?view=sql-server-ver16

Many thanks
Si

**Comment by MarkMpn** [comment] 2022-10-02 19:48
Thanks for the details. It's something I'm intending to add in a future update along with other UI productivity features. I'm closing this as a duplicate of #200 but look out for this in an update over the next few months.

**Closed by MarkMpn** 2022-10-02 19:48 UTC

**Comment by s1m0nj** [comment] 2022-10-27 07:11
OK thanks for the update.
