### ISSUE TITLE
Confirmation dialog for update appears more than 1 time

### ISSUE THREAD

**Issue by sybaris** [MarkMpn/Sql4Cds#195] opened 2022-05-03 14:08 UTC
Hi

When I make this update : 

update savedquery
set fetchxml = ''	
where savedqueryid='7a0ce57e-888d-eb11-a812-000d3adb4c00'

I have 67 times the following dialog box : 

![image](https://user-images.githubusercontent.com/11009997/166468644-41ba5d29-02ec-4edd-ba88-020c4d85bf2e.png)

I think this is a regression from the last update.

Regards
Sybaris

**Comment by MarkMpn** [comment] 2022-05-03 18:49
Duplicate of #191

**Closed** 2022-05-03 18:49 UTC
