### ISSUE TITLE
[Feature Request] A way to extract data from OptionMetadataCollection

### ISSUE THREAD

**Issue by sybaris** [MarkMpn/Sql4Cds#565] opened 2024-10-11 14:36 UTC
Hi,

I would like to get informations from the options of a globaloptionset using SQL
![image](https://github.com/user-attachments/assets/d74bc1e4-af82-4649-a008-23ac753a8402)

Is there a way today ?

Regards
Sybaris

**Comment by MarkMpn** [comment] 2024-10-13 15:45
Closing this as a duplicate of #543

**Closed by MarkMpn** 2024-10-13 15:45 UTC
