### ISSUE TITLE
[Bug] The bypass plugin execution window appears multiple times for a query

### ISSUE THREAD

**Issue by UrSok** [MarkMpn/Sql4Cds#193] opened 2022-04-29 12:39 UTC
The bypass plugin execution window appears multiple times.
Each query run increases the number of times the window appears.

![sad](https://user-images.githubusercontent.com/5286851/165945326-1e57d342-e1f9-4193-bd89-67f6bee7e002.gif)

**Comment by MarkMpn** [comment] 2022-04-29 12:50
Duplicate of #191

**Closed by MarkMpn** 2022-04-29 12:50 UTC
