### ISSUE TITLE
[New feature] Autoexecute a SQL script from the command line

### ISSUE THREAD

**Issue by JMG74** [MarkMpn/Sql4Cds#566] opened 2024-10-14 09:27 UTC
Your Sql4Cds is fantastic for interactive use! Thank's a lot for the time and energy you invested in!! 

Now, I would like to use it (ideally within DevOps pipeline) to prepare data in our Dataverse prior launching automatic tests of our Power Apps model-driven applications. 

Here is the process I can imagine:
1.	Launch Sql4Cds from the command line (on Windows from “.bat” file or from PowerShell script).
2.	Tell it to open a given SQL script (full path name passed at launch time).
3.	Run the script.
4.	Wait until end of processing.
5.	Save the execution log into an output file (name is the script full path name with extension “.log”).
6.	Exit from XrmToolBox.

I’ve read the documentation of XrmToolBox and I discovered that I can launch Sql4Cds plugin directly from the command line by using following syntax (see: [application protocol](https://www.xrmtoolbox.com/documentation/for-developers/implement-application-protocol/)).

> C:\\_myPathToXTB_\XrmToolBox.exe /connection:"_myConnectionToDataverse_" /plugin:"SQL 4 CDS"

As I understand, there's also a 3rd parameter called “data” that we can use to pass extra data to be used by the plugins.
My idea would be to pass the full path to the script to execute… but today your plugin cannot use it and would have to be adapted to read the script, execute it and save the execution log to the output file.

Would you have time to adapt your plugin to allow this use case ?
Many thanks in advance and I remain at your disposal for any complement.

**Comment by MarkMpn** [comment] 2024-10-15 07:41
I don't think XrmToolBox is appropriate for use in a DevOps pipeline, but I do have plans to make it easier to use the library from the command line. I'm going to close this as a duplicate of #381, but I will be looking at this in the next few months.

**Closed by MarkMpn** 2024-10-15 07:41 UTC
